inotify: don't clean up on Close()
This makes the test fail in ~20% of the time on my laptop; e.g.:

    --- FAIL: TestScript/watch-dir/subdir (0.96s)
        helpers_test.go:1030:
            have:
                CREATE   /sub
            want:
                CREATE   /sub
                CREATE   /file
                REMOVE   /sub
                REMOVE   /file
            diff:
                --- have
                +++ want
                @@ -1 +1,4 @@
                -have CREATE   /sub
                +want CREATE   /file
                +want   CREATE   /sub
                +want   REMOVE   /file
                +want   REMOVE   /sub

And other tests are well.

I can never repro it with either `-run=TestScript/watch-dir/subdir` or
`parallel=1`, and it's kind of annoying to debug. Possibly a bug in the
test runner code rather than fsnotify proper(?)

Was added in #756 for parity with changes in kqueue; no one actually
reported a problem and it's been like this for 15 years. I say it's
probably just okay to revert for now.